name: build

env:
  GO_VERSION: 1.20

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      
    - name: Authenticate with GitHub
      uses: docker/login-action@v1
      with:
        registry: https://docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Install private dependencies
      run: go mod tidy
      
    - name: Run tests
      run: go test ./...
      
    - name: Build
      run: |
        for OS in linux windows darwin; do
          for ARCH in amd64 arm64; do
            GOOS=$OS GOARCH=$ARCH go build -o "whatsapp_${OS}_${ARCH}" ./cmd
          done
        done
      
    - name: Upload artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v2
      with:
        name: "whatsapp-${{ github.ref }}-$OS-$ARCH"
        path: |
          whatsapp_linux_amd64
          whatsapp_linux_arm64
          whatsapp_windows_amd64.exe
          whatsapp_windows_arm64.exe
          whatsapp_macos_amd64
          whatsapp_macos_arm64

